// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.5.1
// source: pod.proto

package pod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodId            uint64     `protobuf:"varint,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	PodName          string     `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace     string     `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodTeamId        int64      `protobuf:"varint,4,opt,name=pod_team_id,json=podTeamId,proto3" json:"pod_team_id,omitempty"`
	PodMaxCpuUsage   float32    `protobuf:"fixed32,5,opt,name=pod_max_cpu_usage,json=podMaxCpuUsage,proto3" json:"pod_max_cpu_usage,omitempty"`
	PodMaxMemUsage   float32    `protobuf:"fixed32,6,opt,name=pod_max_mem_usage,json=podMaxMemUsage,proto3" json:"pod_max_mem_usage,omitempty"`
	PodEnvs          []*PodEnv  `protobuf:"bytes,7,rep,name=pod_envs,json=podEnvs,proto3" json:"pod_envs,omitempty"`
	PodPorts         []*PodPort `protobuf:"bytes,8,rep,name=pod_ports,json=podPorts,proto3" json:"pod_ports,omitempty"`
	Image            string     `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	PodPullPolicy    string     `protobuf:"bytes,10,opt,name=pod_pull_policy,json=podPullPolicy,proto3" json:"pod_pull_policy,omitempty"`
	PodRestartPolicy string     `protobuf:"bytes,11,opt,name=pod_restart_policy,json=podRestartPolicy,proto3" json:"pod_restart_policy,omitempty"`
	PodDeployType    string     `protobuf:"bytes,12,opt,name=pod_deploy_type,json=podDeployType,proto3" json:"pod_deploy_type,omitempty"`
	Replicas         int32      `protobuf:"varint,13,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{0}
}

func (x *PodInfo) GetPodId() uint64 {
	if x != nil {
		return x.PodId
	}
	return 0
}

func (x *PodInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodInfo) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *PodInfo) GetPodTeamId() int64 {
	if x != nil {
		return x.PodTeamId
	}
	return 0
}

func (x *PodInfo) GetPodMaxCpuUsage() float32 {
	if x != nil {
		return x.PodMaxCpuUsage
	}
	return 0
}

func (x *PodInfo) GetPodMaxMemUsage() float32 {
	if x != nil {
		return x.PodMaxMemUsage
	}
	return 0
}

func (x *PodInfo) GetPodEnvs() []*PodEnv {
	if x != nil {
		return x.PodEnvs
	}
	return nil
}

func (x *PodInfo) GetPodPorts() []*PodPort {
	if x != nil {
		return x.PodPorts
	}
	return nil
}

func (x *PodInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PodInfo) GetPodPullPolicy() string {
	if x != nil {
		return x.PodPullPolicy
	}
	return ""
}

func (x *PodInfo) GetPodRestartPolicy() string {
	if x != nil {
		return x.PodRestartPolicy
	}
	return ""
}

func (x *PodInfo) GetPodDeployType() string {
	if x != nil {
		return x.PodDeployType
	}
	return ""
}

func (x *PodInfo) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type PodEnv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EnvKey   string `protobuf:"bytes,2,opt,name=env_key,json=envKey,proto3" json:"env_key,omitempty"`
	EnvValue string `protobuf:"bytes,3,opt,name=env_value,json=envValue,proto3" json:"env_value,omitempty"`
}

func (x *PodEnv) Reset() {
	*x = PodEnv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodEnv) ProtoMessage() {}

func (x *PodEnv) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodEnv.ProtoReflect.Descriptor instead.
func (*PodEnv) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{1}
}

func (x *PodEnv) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PodEnv) GetEnvKey() string {
	if x != nil {
		return x.EnvKey
	}
	return ""
}

func (x *PodEnv) GetEnvValue() string {
	if x != nil {
		return x.EnvValue
	}
	return ""
}

type PodPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *PodPort) Reset() {
	*x = PodPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodPort) ProtoMessage() {}

func (x *PodPort) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodPort.ProtoReflect.Descriptor instead.
func (*PodPort) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{2}
}

func (x *PodPort) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PodPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PodPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type PodId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PodId) Reset() {
	*x = PodId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodId) ProtoMessage() {}

func (x *PodId) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodId.ProtoReflect.Descriptor instead.
func (*PodId) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3}
}

func (x *PodId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FinadAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinadAll) Reset() {
	*x = FinadAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pod_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinadAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinadAll) ProtoMessage() {}

func (x *FinadAll) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinadAll.ProtoReflect.Descriptor instead.
func (*FinadAll) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{5}
}

type AllPod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodInfo []*PodInfo `protobuf:"bytes,1,rep,name=pod_info,json=podInfo,proto3" json:"pod_info,omitempty"`
}

func (x *AllPod) Reset() {
	*x = AllPod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pod_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllPod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPod) ProtoMessage() {}

func (x *AllPod) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPod.ProtoReflect.Descriptor instead.
func (*AllPod) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{6}
}

func (x *AllPod) GetPodInfo() []*PodInfo {
	if x != nil {
		return x.PodInfo
	}
	return nil
}

var File_pod_proto protoreflect.FileDescriptor

var file_pod_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xdd, 0x03, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15,
	0x0a, 0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x70, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x70, 0x6f, 0x64, 0x5f, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x6f, 0x64, 0x54,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x11, 0x70, 0x6f, 0x64, 0x5f, 0x6d, 0x61, 0x78,
	0x5f, 0x63, 0x70, 0x75, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0e, 0x70, 0x6f, 0x64, 0x4d, 0x61, 0x78, 0x43, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x29, 0x0a, 0x11, 0x70, 0x6f, 0x64, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x5f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x70, 0x6f, 0x64,
	0x4d, 0x61, 0x78, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x70,
	0x6f, 0x64, 0x5f, 0x65, 0x6e, 0x76, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x64, 0x45, 0x6e, 0x76, 0x52, 0x07, 0x70, 0x6f,
	0x64, 0x45, 0x6e, 0x76, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x6f, 0x64, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6f, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x08, 0x70, 0x6f, 0x64, 0x50, 0x6f, 0x72,
	0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x6f, 0x64, 0x5f,
	0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x70, 0x6f, 0x64, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x12, 0x2c, 0x0a, 0x12, 0x70, 0x6f, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x6f,
	0x64, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x26,
	0x0a, 0x0f, 0x70, 0x6f, 0x64, 0x5f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x6f, 0x64, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x73, 0x22, 0x4e, 0x0a, 0x06, 0x50, 0x6f, 0x64, 0x45, 0x6e, 0x76, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x65, 0x6e, 0x76, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x6e, 0x76, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x76, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x49, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x17, 0x0a,
	0x05, 0x50, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x0a, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x61, 0x64, 0x41, 0x6c, 0x6c,
	0x22, 0x33, 0x0a, 0x06, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f,
	0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xf1, 0x01, 0x0a, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x2b, 0x0a,
	0x06, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x64, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0b, 0x46, 0x69,
	0x6e, 0x64, 0x50, 0x6f, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x64, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x6f, 0x64, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a, 0x46, 0x69, 0x6e,
	0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x46, 0x69, 0x6e, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x64, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x70, 0x6f,
	0x64, 0x3b, 0x70, 0x6f, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pod_proto_rawDescOnce sync.Once
	file_pod_proto_rawDescData = file_pod_proto_rawDesc
)

func file_pod_proto_rawDescGZIP() []byte {
	file_pod_proto_rawDescOnce.Do(func() {
		file_pod_proto_rawDescData = protoimpl.X.CompressGZIP(file_pod_proto_rawDescData)
	})
	return file_pod_proto_rawDescData
}

var file_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pod_proto_goTypes = []interface{}{
	(*PodInfo)(nil),  // 0: proto.PodInfo
	(*PodEnv)(nil),   // 1: proto.PodEnv
	(*PodPort)(nil),  // 2: proto.PodPort
	(*PodId)(nil),    // 3: proto.PodId
	(*Response)(nil), // 4: proto.response
	(*FinadAll)(nil), // 5: proto.FinadAll
	(*AllPod)(nil),   // 6: proto.AllPod
}
var file_pod_proto_depIdxs = []int32{
	1, // 0: proto.PodInfo.pod_envs:type_name -> proto.PodEnv
	2, // 1: proto.PodInfo.pod_ports:type_name -> proto.PodPort
	0, // 2: proto.AllPod.pod_info:type_name -> proto.PodInfo
	0, // 3: proto.Pod.AddPod:input_type -> proto.PodInfo
	0, // 4: proto.Pod.DeletePod:input_type -> proto.PodInfo
	3, // 5: proto.Pod.FindPodById:input_type -> proto.PodId
	0, // 6: proto.Pod.UpdatePod:input_type -> proto.PodInfo
	5, // 7: proto.Pod.FindAllPod:input_type -> proto.FinadAll
	4, // 8: proto.Pod.AddPod:output_type -> proto.response
	4, // 9: proto.Pod.DeletePod:output_type -> proto.response
	0, // 10: proto.Pod.FindPodById:output_type -> proto.PodInfo
	4, // 11: proto.Pod.UpdatePod:output_type -> proto.response
	6, // 12: proto.Pod.FindAllPod:output_type -> proto.AllPod
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pod_proto_init() }
func file_pod_proto_init() {
	if File_pod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodEnv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pod_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinadAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pod_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllPod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pod_proto_goTypes,
		DependencyIndexes: file_pod_proto_depIdxs,
		MessageInfos:      file_pod_proto_msgTypes,
	}.Build()
	File_pod_proto = out.File
	file_pod_proto_rawDesc = nil
	file_pod_proto_goTypes = nil
	file_pod_proto_depIdxs = nil
}
